weather_warehouse:
  target: weather
  outputs:
    weather:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      port: "{{ env_var('CLICKHOUSE_PORT') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      database: "{{ env_var('CLICKHOUSE_DATABASE') }}"
      schema: "{{ env_var('CLICKHOUSE_DATABASE') }}"