# Minimal Airflow Helm Chart Configuration for Scaleway
images:
  airflow:
    repository: rg.fr-par.scw.cloud/weather-etl-dev/airflow-with-dags
    tag: "latest"
    pullPolicy: Always

# Airflow version
airflowVersion: "3.0.2"

# Minimal resource configuration
executor: "KubernetesExecutor"

# Redis configuration for CeleryExecutor (disabled for minimal setup)
redis:
  enabled: false

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: "postgres"
    username: "airflow"
    password: "airflow"
    database: "airflow"
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

# Scheduler configuration
scheduler:
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Webserver configuration
webserver:
  enabled: true
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Triggerer configuration
triggerer:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Non-sensitive environment variables
env:
  - name: CLICKHOUSE_HOST
    value: "clickhouse.clickhouse.svc.cluster.local"
  - name: CLICKHOUSE_PORT
    value: "8123"
  - name: CLICKHOUSE_USER
    value: "airflow_dbt"
  - name: CLICKHOUSE_DATABASE
    value: "weather"
  - name: ENVIRONMENT
    value: "dev"

# Secret environment variables (CORRECTED SYNTAX)
secret:
  - envName: "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_SECRET"
    secretName: "airflow-secrets"
    secretKey: "postgres-password"
  - envName: "CLICKHOUSE_PASSWORD"
    secretName: "clickhouse-connection-secret"
    secretKey: "clickhouse-password"
  - envName: "GEOCODING_API_KEY"
    secretName: "external-api-secrets"
    secretKey: "geocoding-api-key"
  - envName: "SCALEWAY_ACCESS_KEY"
    secretName: "external-api-secrets"
    secretKey: "scaleway-access-key"
  - envName: "SCALEWAY_SECRET_KEY"
    secretName: "external-api-secrets"
    secretKey: "scaleway-secret-key"
  - envName: "S3_ACCESS_KEY"
    secretName: "external-api-secrets"
    secretKey: "s3-access-key"
  - envName: "S3_SECRET_KEY"
    secretName: "external-api-secrets"
    secretKey: "s3-secret-key"

# Airflow configuration
config:
  webserver:
    expose_config: 'True'
  logging:
    logging_level: 'INFO'
  scheduler:
    catchup_by_default: 'False'

# Logs configuration
# TO BE FIXED - issue with persistent volume claim on default storage class on Scaleway
#logs:
#  persistence:
#    enabled: true
#    size: 5Gi

# Default user credentials from secrets
webserverSecretKeySecretName: "airflow-secrets"
defaultUser:
  enabled: true
  role: Admin
  username: admin
  email: admin@example.com
  firstName: admin
  lastName: user
  passwordSecret: "airflow-secrets"
  passwordSecretKey: "admin-password"